config/routes.rb
Rails.application.routes.draw do
  root 'locations#index'
  resources :companies
  resources :locations
  resources :vehicles
  # devise_for :users, :controllers => { registrations: 'registrations'}
  devise_for :users
  resources :users
  namespace :admin do
    resources :settings
  end
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  cache_prefix { "v1" }

  # Define your fields
  # field :host, type: :string, default: "http://localhost:3000"
  # field :default_locale, default: "en", type: :string
  # field :confirmable_enable, default: "0", type: :boolean
  # field :admin_emails, default: "admin@rubyonrails.org", type: :array
  # field :omniauth_google_client_id, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] || ""), type: :string, readonly: true
  # field :omniauth_google_client_secret, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] || ""), type: :string, readonly: true
  field :two_day_rate, type: :integer, default: 2
  field :three_day_rate, type: :integer, default: 3
  field :weekly_rate, type: :integer, default: 5
  field :drop_off_pickup_rate, type: :integer, default: 2
  field :delivery_title_one_trip, type: :string, default: "Delivery"
  field :delivery_description_one_trip, type: :string, default: "Vehicle is on site for duration."
  field :delivery_title_two_trips, type: :string, default: "Drop Off & Pick Up"
  field :delivery_description_two_trips, type: :string, default: "Vehicle and driver make two trips to location."
end

app/controllers/admin/settings_controller.rb
module Admin
  class SettingsController < ApplicationController
    before_action :get_setting, only: [:edit, :update]

    def index
      @settings = Setting
    end

    def edit
    end

    def update
      if @setting.value != params[:setting][:value]
        @setting.value = params[:setting][:value]
        @setting.save
        redirect_to admin_settings_path, notice: 'Setting has updated.'
      else
        redirect_to admin_settings_path
      end
    end

    def get_setting
      @setting = Setting.find_by(var: params[:id]) || Setting.new(var: params[:id])
    end
  end
end

app/views/admin/settings/_app.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">App Settings</h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Delivery Title</dt>
      <dd><%= Setting.delivery_title_one_trip %> <%= link_to 'Edit', edit_admin_setting_path("delivery_title_one_trip"), class: 'btn btn-default btn-xs btn-hover' %></dd>
      <dt>Description:</dt>
      <dd><%= Setting.delivery_description_one_trip %> <%= link_to 'Edit', edit_admin_setting_path("delivery_description_one_trip"), class: 'btn btn-default btn-xs btn-hover' %></dd>
      <dt>Delivery & Pickup Title:</dt>
      <dd><%= Setting.delivery_title_two_trips %></td> <%= link_to 'Edit', edit_admin_setting_path("delivery_title_two_trips"), class: 'btn btn-default btn-xs btn-hover' %></dd>
      <dt>Description:</dt>
      <dd><%= Setting.delivery_description_two_trips %> <%= link_to 'Edit', edit_admin_setting_path("delivery_description_two_trips"), class: 'btn btn-default btn-xs btn-hover' %></dd>
    </dl>
  </div>
</div>

app/views/admin/settings/_rates.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Formula Settings</h3>
  </div>
  <div class="panel-body">
      <dl class="dl-horizontal">
        <dt>Two Day Rate:</dt>
        <dd><%= Setting.two_day_rate %> <%= link_to 'Edit', edit_admin_setting_path("two_day_rate"), class: 'btn btn-default btn-xs btn-hover' %></dd>
        <dt>Three Day Rate:</dt>
        <dd><%= Setting.three_day_rate %> <%= link_to 'Edit', edit_admin_setting_path("three_day_rate"), class: 'btn btn-default btn-xs btn-hover' %></dd>
        <dt>Weekly Rate:</dt>
        <dd><%= Setting.weekly_rate %> <%= link_to 'Edit', edit_admin_setting_path("weekly_rate"), class: 'btn btn-default btn-xs btn-hover' %></dd>
        <dt>Drop Off & Pickup Rate:</dt>
        <dd><%= Setting.drop_off_pickup_rate %> <%= link_to 'Edit', edit_admin_setting_path("drop_off_pickup_rate"), class: 'btn btn-default btn-xs btn-hover' %></dd>
      </dl>
  </div>
</div>

app/views/admin/settings/edit.html.erb
<div class="container">
  <h1 class="page-header">Settings Edit</h1>
  <%= simple_form_for(@setting, url: admin_setting_path(@setting.var), method: 'patch') do |f| %>
  <label><%= @setting.var.humanize %></label>
    <div class="row">
      <div class="col-sm-5">
        <div class="row">
          <div class="col-sm-10">
            <%= f.text_field :value, label: false, class: 'form-control' %>
          </div>
          <div class="col-sm-2">
            <%= f.button :submit, class: btn_classes_create %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/settings/index.html.erb
<div class="container">
  <h1 class="page-header">Settings</h1>
  <div class="row">
    <div class="col-md-4">
      <%= render 'rates' %>
    </div>
    <div class="col-md-8">
      <h4>1. Driver</h4>
      <p><code>@driver = @time * vehicle.driver_rate / 60 * 2</code></p>
      <h4>2. Vehicle Rate</h4>
      <p><code>@round_trip = @mileage / vehicle.mpg * vehicle.fuel_rate + (@mileage * vehicle.per_mile_rate + vehicle.rental_rate )</code></p>
      <h4>3. Final Rate</h4>
      <p>Single Day: <code>@round_trip + @driver</code></p>
      <p>Two Day: <code>@round_trip * Setting.two_day_rate + @driver</code></p>
      <p>Three Day: <code>@round_trip * Setting.three_day_rate + @driver</code></p>
      <p>Weekly Day: <code>@round_trip * Setting.weekly_rate + @driver</code></p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-6">
      <%= render 'app' %>
    </div>
  </div>
</div>