config/routes.rb
Rails.application.routes.draw do
  root 'locations#index'
  resources :companies
  resources :locations
  resources :vehicles
  # devise_for :users, :controllers => { registrations: 'registrations'}
  devise_for :users
  resources :users
  namespace :admin do
    resources :settings
  end
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id           :integer          not null, primary key
#  address      :string
#  latitude     :float
#  longitude    :float
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  city         :string
#  state        :string
#  postal_code  :string
#  full_address :string
#  title        :string
#

class Location < ActiveRecord::Base
  validates :title, :presence => true
  validates :address, :presence => true
  
  default_scope { order('title ASC') }
  
  # geocoded_by :address
  # reverse_geocoded_by :latitude, :longitude, :address => :full_address
  # reverse_geocoded_by :latitude, :longitude
  # geocoded_by :full_address
  # after_validation :geocode, :if => :address_changed?
  # after_validation :reverse_geocode, :if => :address_changed?

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo = results.first
      # populate your model
      obj.full_address  = geo.street_address
      obj.city          = geo.city
      obj.state         = geo.state
      obj.postal_code   = geo.postal_code
    end
  end
  # after_validation :reverse_geocode  # auto-fetch address
  after_validation :reverse_geocode, :if => :address_changed?
  # after_validation :fetch_address
  
  # after_validation :geocode, :if => :address_changed?
  
  def street_address
    [full_address, city, state, postal_code].compact.join(', ')
  end
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /locations
  # GET /locations.json
  def index
    
    # @q = Location.ransack(params[:q])
    # @locations = @q.result(distinct: true)
    
    @q = Location.ransack(params[:q])
    @locations = @q.result.paginate(:page => params[:page], :per_page => 10)
    
    @total_locations = Location.all.count
    
    # if params[:q]
    #   @q = Location.ransack(params[:q])
    #   @locations = Location.tagged_with(params[:tag])
    # else
    #   @q = Location.ransack(params[:q])
    #   @locations = @q.result.includes(:artist, :event).paginate(:page => params[:page], :per_page => 10)
    # end
    # authorize Location
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @vehicles = Vehicle.all
    @location = Location.find(params[:id])
    @warehouseAddress = '1000 Cottage Grove SE, Grand Rapids, MI 49507'
    if params[:warehouse] == 'Florida'
      @warehouseAddress = 'Clearwater, Florida'
    end
    # authorize @location
    
    gmaps = GoogleMapsService::Client.new
    @routes = gmaps.directions(
      @warehouseAddress,
      @location.try(:address),
      mode: 'driving',
      alternatives: false)
    
    @time = @routes[0][:legs][0][:duration][:value] / 60
    @mileage = @routes[0][:legs][0][:distance][:text].chomp(' mi').to_i
    
    # @street_address = @location.try(:full_address) + ', ' + @location.try(:city) + ', ' + @location.try(:state) + ', ' + @location.try(:postal_code)
  end

  # GET /locations/new
  def new
    @location = Location.new
    @q = Location.ransack(params[:q])
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:title, :address, :city, :state, :postal_code, :latitude, :longitude)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-group">
    <%= f.input :title, class: 'form-control', required: "true" %>
    <span id="helpBlock" class="help-block">The name of this location. Example: <strong>On Stage Services</strong></span>
  </div>

  <div class="form-group">
    <%= f.input :address, class: 'form-control' %>
    <span id="helpBlock" class="help-block">The actual street address of the location. Example: <strong>1000 Cottage Grove St. SE, Grand Rapids, MI 49507</strong></span>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: btn_classes_create %>
  </div>
<% end %>

app/views/locations/_form_edit.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :title, class: 'form-control', required: "true" %>
    <span id="helpBlock" class="help-block">The name of this location. Example: <strong>On Stage Services</strong></span>
  </div>

  <div class="form-group">
    <%= f.input :address, class: 'form-control' %>
    <span id="helpBlock" class="help-block">The actual street address of the location. Example: <strong>1000 Cottage Grove St. SE, Grand Rapids, MI 49507</strong></span>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.input :latitude, class: 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.input :longitude, class: 'form-control' %>
      </div>
    </div>
  </div>


  <div class="form-actions">
    <%= f.button :submit, class: btn_classes_create %>
  </div>
<% end %>

app/views/locations/_maps.html.erb
<div id="location-json" data-location="<%= @location.to_json %>"></div>
<div class="row">
  <div class="col-sm-6">
    <div id="map-pin">
      <div class="well" style="width: 100%;height:200px;"></div>
    </div>
  </div>
  <div class="col-sm-6">
    <div id="map-satellite">
      <div class="well" style="width: 100%;height:200px;"></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div id="map-directions">
      <div class="well" style="width: 100%;height:300px;"></div>
    </div>
  </div>
</div>

app/views/locations/_rates.html.erb
<h3><%= Setting.delivery_title_one_trip %><br/><small><%= Setting.delivery_description_one_trip %></small></h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Vehicle</th>
      <th class="text-right fit">Driver</th>
      <th class="text-right fit">Duration</th>
      <th class="text-right fit">Vehicle</th>
      <th class="text-right fit">Total</th>
    </tr>
  </thead>
  <tbody>
  <% @vehicles.order(:order).each do |vehicle| %>
    <div class="well hidden debug container">
      <h3>Debug</h3>
      <!-- <p>Google Directions API <code><%#= @directions.status %></code> 'google_directions' gem</p> -->
      <p>vehicle.driver_rate: <code><%= vehicle.driver_rate %></code></p>
      <p>vehicle.rental_rate: <code><%= vehicle.rental_rate %></code></p>
      <p>vehicle.fuel_rate: <code><%= vehicle.fuel_rate %></code></p>
      <p>vehicle.mpg: <code><%= vehicle.mpg %></code></p>
      <p>vehicle.per_mile_rate: <code><%= vehicle.per_mile_rate %></code></p>
      <p>@time = @directions.drive_time_in_minutes: <code><%#= @directions.drive_time_in_minutes %></code></p>
      <p>@mileage = @directions.distance_in_miles: <code><%#= @directions.distance_in_miles %></code></p>
      <p>@driver: <code><%= @driver = @time * vehicle.driver_rate / 60 * 2 %></code><br><small>(@driver = @time * vehicle.driver_rate / 60 * 2)</small></p>
      <p>@round_trip: <code><%= @round_trip = (@mileage / vehicle.mpg * vehicle.fuel_rate + (@mileage * vehicle.per_mile_rate + vehicle.rental_rate )).round(2) %></code><br><small>(@round_trip = (@mileage / vehicle.mpg * vehicle.fuel_rate + (@mileage * vehicle.per_mile_rate + vehicle.rental_rate )).round(2)</small></p>
    </div>
    <% @driver = @time * vehicle.driver_rate / 60 * 2 %>
    <% @round_trip = (@mileage / vehicle.mpg * vehicle.fuel_rate + (@mileage * vehicle.per_mile_rate + vehicle.rental_rate )).round(2) %>
      <tr>
        <td>
          <h4><%= link_to vehicle.title, vehicle %></h4>
        </td>
        <td class="fit text-right"><small>$</small><%= number_with_precision(@driver, :precision => 2) %></td>
        <td class="fit text-right">
          <span class="text-muted">1 day </span></small><br>
          <span class="text-muted">2 days </span></small><br>
          <span class="text-muted">3 days </span></small><br>
          <span class="text-muted">week </span></small>
        </td>
        <td class="fit text-right"><small>$</small><span data-toggle="tooltip" title="Round Trip ($<%= number_with_precision(@round_trip, :precision => 2) %>)"><%= number_with_precision(@round_trip, :precision => 2) %></span><br>
        <small>$</small><span data-toggle="tooltip" title="Round Trip x Two Day Rate ($<%= number_with_precision(@round_trip, :precision => 2) %> x <%= Setting.two_day_rate.to_f %>)"><%= number_with_precision(@round_trip * Setting.two_day_rate.to_f, :precision => 2) %></span><br>
        <small>$</small><span data-toggle="tooltip" title="Round Trip x Three Day Rate ($<%= number_with_precision(@round_trip, :precision => 2) %> x <%= Setting.three_day_rate.to_f %>)"><%= number_with_precision(@round_trip * Setting.three_day_rate.to_f, :precision => 2) %></span><br>
        <small>$</small><span data-toggle="tooltip" title="Round Trip x Weekly Rate ($<%= number_with_precision(@round_trip, :precision => 2) %> x <%= Setting.weekly_rate.to_f %>)"><%= number_with_precision(@round_trip * Setting.weekly_rate.to_f, :precision => 2) %></span><br></td>
        <td class="fit text-right"><small>$</small><span data-toggle="tooltip" title="Round Trip + Driver ($<%= number_with_precision(@round_trip, :precision => 2) %> + $<%= @driver %>)"><%= number_with_precision(@round_trip + @driver, :precision => 2) %></span><br>
        <span class="text-right"><small>$</small><span data-toggle="tooltip" title="Round Trip x Two Day Rate + Driver ($<%= number_with_precision(@round_trip, :precision => 2) %> x <%= Setting.two_day_rate.to_f %> + $<%= number_with_precision(@driver, :precision => 2) %>)"><%= number_with_precision(@round_trip * Setting.two_day_rate.to_f + @driver, :precision => 2) %></span><br>
        <span class="text-right"><small>$</small><span data-toggle="tooltip" title="Round Trip x Three Day Rate + Driver ($<%= number_with_precision(@round_trip, :precision => 2) %> x <%= Setting.three_day_rate.to_f %> + $<%= number_with_precision(@driver, :precision => 2) %>)"><%= number_with_precision(@round_trip * Setting.three_day_rate.to_f + @driver, :precision => 2) %></span><br>
        <span class="text-right"><small>$</small><span data-toggle="tooltip" title="Round Trip x Weekly Rate + Driver ($<%= number_with_precision(@round_trip, :precision => 2) %> x <%= Setting.weekly_rate.to_f %> + $<%= number_with_precision(@driver, :precision => 2) %>)"><%= number_with_precision(@round_trip * Setting.weekly_rate.to_f + @driver, :precision => 2) %></span></td>
      </tr>
      <tr>
        <td colspan="5" class="text-center">
          <small><span class="text-muted">miles/<%= vehicle.mpg %> mpg x $<%= number_with_precision(vehicle.fuel_rate, :precision => 2) %>/gal + (miles + <%= vehicle.per_mile_rate %> per mile + $<%= vehicle.rental_rate %> rental)</span></small>
        </td>
      </td>
  <% end %>
  </tbody>
</table>
<h3><%= Setting.delivery_title_two_trips %><br/><small><%= Setting.delivery_description_two_trips %></small></h3>
<table class="table">
  <thead>
    <tr>
      <th>Vehicle</th>
      <th class="text-right fit">Driver</th>
      <th class="text-right fit">Vehicle</th>
      <th class="text-right fit">Total</th>
    </tr>
  </thead>
  <tbody>
  <% @vehicles.order(:order).each do |vehicle| %>
  <% @driver = (@time * vehicle.driver_rate / 60 * Setting.drop_off_pickup_rate.to_f) %>
  <% @round_trip = (@mileage / vehicle.mpg * vehicle.fuel_rate + (@mileage * vehicle.per_mile_rate + vehicle.rental_rate )).round(2) %>
    <tr>
      <td>
        <h4><%= link_to vehicle.title, vehicle %></h4>
      </td>
      <td class="text-right"><small>$</small><span data-toggle="tooltip" title="Driver x Drop Pick ($<%= number_with_precision(@driver, :precision => 2) %> x <%= Setting.drop_off_pickup_rate.to_f %>)"><%= number_with_precision(@driver * Setting.drop_off_pickup_rate.to_f, :precision => 2) %></span></td>
      <td class="text-right"><small>$</small><span data-toggle="tooltip" title="Round Trip x Drop Pick ($<%= number_with_precision(@round_trip, :precision => 2) %> x <%= Setting.drop_off_pickup_rate.to_f %>)"><%= number_with_precision(@round_trip * Setting.drop_off_pickup_rate.to_f, :precision => 2) %><span></td>
      <td class="text-right"><small>$</small><span data-toggle="tooltip" title="(Driver + Round Trip) x Drop Pick ($<%= number_with_precision(@driver, :precision => 2) %> + $<%= number_with_precision(@round_trip, :precision => 2) %> x <%= Setting.drop_off_pickup_rate.to_f %>)"><%= number_with_precision((@driver + @round_trip) * Setting.drop_off_pickup_rate.to_f, :precision => 2) %></span></td>
    </tr>
    <tr>
      <td colspan="5" class="text-center">
        <small><span class="text-muted">miles/<%= vehicle.mpg %> mpg x $<%= number_with_precision(vehicle.fuel_rate, :precision => 2) %>/gal + (miles + <%= vehicle.per_mile_rate %> per mile + $<%= vehicle.rental_rate %> rental)</span></small>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/locations/edit.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-7">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">Edit Location</h1>
      </div>

      <div class="panel-body">
        <%= render 'form_edit' %>
      </div>

    </div>

    <%= link_to 'Back', @location %>
  </div>
</div>

app/views/locations/index.html.erb
<%= render 'layouts/jumbo' unless user_signed_in? %>

<h2>Locations <span class="badge badge-info"><%= @total_locations %></span></h2>

<%= render 'layouts/results' %>

<!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#" aria-controls="home" role="tab" data-toggle="tab">Locations</a></li>
    <li role="presentation"><%= link_to raw('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Location'), new_location_path %></li>
  </ul>

<table class="<%= table_classes %>">
  <thead>
    <tr>
      <th><%= sort_link(@q, :title, 'Title', default_order: :desc) %></th>
      <th><%= sort_link(@q, :city, 'City') %></th>
      <th><%= sort_link(@q, :state, 'State') %></th>
      <th><%= sort_link(@q, :postal_code, 'Postal Code') %></th>
      <th class="text-center">Google Map</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td>
          <h4><%= link_to location.title, location, class: 'location-link' %></h4>
          <span class="text-muted"><%= location.try(:address) %></span>
        </td>
        <td><%= location.try(:city) %></td>
        <td><%= location.try(:state) %></td>
        <td><%= location.try(:postal_code) %></td>
        <td class="text-center"><%= link_to raw('<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Map'), "http://maps.google.com/?q="+location.address, :target => "_blank" %></td>
        <td><%= link_to 'Edit', edit_location_path(location), class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
 <%= will_paginate @locations, renderer: BootstrapPagination::Rails %>
 <p><small>Showing <%= @locations.count %> of <%= @total_locations %> locations.</small></p>
</div>

app/views/locations/new.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-7">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">New Location</h1>
      </div>
      
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    
    </div>
    
    <%= link_to 'Back', locations_path %>
  </div>
</div>

app/views/locations/show.html.erb
<h2><%= @location.title %> <small style="font-size: 14px;"><span class="glyphicon glyphicon-road" aria-hidden="true"></span>
    <span id="distance"></span>, <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
    <span id="duration"></span> &mdash; <span id="summary"></span></small>
    <%= link_to 'Edit', edit_location_path(@location), class: 'btn btn-primary pull-right' %></h2>

<div class="row">
  <div class="col-sm-8">
    <em><%= @location.try(:address) %></em>
    <%= link_to raw('<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Map'), "http://maps.google.com/?q="+@location.address, :target => "_blank", :class => "btn btn-link" %>

    <%= render 'locations/maps' %>

    <table class="table">
      <tr>
        <th>Latitude</th>
        <th>Longitude</th>
      </tr>
      <tr>
        <td><div id="latitude"><%= @location.latitude %></div></td>
        <td><div id="longitude"><%= @location.longitude %></div></td>
      </tr>
    </table>
    </ul>
  </div>
  <div class="col-sm-4">
    <%= render 'locations/rates' %>
  </div>
</div>

<script>
  var directions = <%= raw @routes.to_json %>;
  // console.log(directions);
</script>