config/routes.rb
Rails.application.routes.draw do
  root 'locations#index'
  resources :companies
  resources :locations
  resources :vehicles
  # devise_for :users, :controllers => { registrations: 'registrations'}
  devise_for :users
  resources :users
  namespace :admin do
    resources :settings
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to raw('<span class="glyphicon glyphicon-road" aria-hidden="true"></span> Locations & Miles'), root_path, class: 'navbar-brand' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <%= render 'layouts/search' %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Warehouses"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> <span id="currentWarehouse">Warehouses</span> <span class="caret"></span></a>
          <ul class="dropdown-menu" id="warehouses">
          </ul>
        </li>
        <li>
          <%= link_to(vehicles_path) do %>
            <%= fa_icon "truck", text: "Vehicles" %>
          <% end %>
        </li>
        <li>
          <%= link_to(locations_path) do %>
            <%= fa_icon "map", text: "Locations" %>
          <% end %>
        </li>
        <% if current_user.admin? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Settings', admin_settings_path %></li>
          </ul>
        </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to raw('<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit Profile'), edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to raw('<span class="glyphicon glyphicon-off" aria-hidden="true"></span> Log Out'), destroy_user_session_path, method: 'delete' %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to raw('<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Log In'), new_user_session_path %></li>
        <li><%= link_to "Join", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_jumbo.html.erb
<div class="jumbotron">
  <h1>Welcome to my Pintrested App!</h1>
  <p>This is the home page.</p>
  <div class="center">
    <% unless user_signed_in? %>
      <%= link_to raw('<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Log In'), new_user_session_path, class: "btn btn-default" %>
      <%= link_to "Join", new_user_registration_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_results.html.erb
<% if !@q.title_or_address_cont.nil? %>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="well well-sm">
        <% if @locations.count > 1 %>
          <%= content_tag(:p, "#{@locations.count} results for") %>
        <% elsif @locations.count == 1 %>
          <%= content_tag(:p, "#{@locations.count} result for") %>
        <% else %>
          <p>No results for</p>
        <% end %>
          <h3><%= content_tag(:strong, @q.title_or_address_cont) %></h3>
        <% if @locations.count < 1 %>
          <%= link_to 'Add location', new_location_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_search.html.erb
<%= search_form_for @q, :html => {:class => "navbar-form navbar-left", :name => "search"} do |f| %>
  
  <% if current_page?(root_path) %>
    <%= f.search_field :title_or_address_cont, class: 'form-control', autofocus: 'true' %>
  <% else %>
    <%= f.search_field :title_or_address_cont, class: 'form-control' %>
  <% end %>

  <%= f.submit 'Go', class: 'btn btn-primary' %>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delivery Rate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="google-site-verification" content="9u6uaKhrcPxbqxu_UTG9yMygqOAnzMDGKjHLdojMaGw" />
  <%= render 'favicon' %>
</head>
<body>

  <div class="container-fluid">
    <% if user_signed_in? %>
      <%= render 'layouts/header' %>
    <% end %>
  </div>

  <div class="container-fluid">
    <% flash.each do |name, msg| %>
      <%# content_tag(:div, msg, class: "alert alert-#{name}") %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>